#:schema node_modules/wrangler/config-schema.json
name = "doh"
main = "workers.ts"
compatibility_date = "2024-08-15"
workers_dev = true
preview_urls = false

[[d1_databases]]
binding = "geolite2_country"
database_name = "geoip_20260901_weur"
database_id = "49af07f7-8c2b-4196-9746-24dd0e6d4342"
